### ISSUE TITLE
Investigate heavier caching for class list

### ISSUE THREAD

**Issue by ghost** [php-integrator/core#45]
The global class list is currently not cached. `atom-autocompletion` refetches it after every reindex (debounced by a couple of seconds to avoid constantly fetching a large amount of data). We should investigate removing that limitation client side and simply cache it server side.

The main issue is that we need to minimize cache clears on the class list server side. Simply clearing the entire cache on every file index will cause the cache to hit seldomly. Another way might be to make the indexer somehow intelligently determine if the class list needs to be updated, i.e. it could make a hash of the old list of class names (before the index) and a hash of the new list of class names (after the index) and only clear the cache if they are not equal. Even better would be if the class list cache was not cleared at all, but only invalidated for the class that was updated.

**Comment by Gert-dev** [comment]
I did some refactoring, but it turns out that this isn't slow at all. All the server side does is fetch a list of classes (one SQL call) and then turn that array into another array - which is just a single method call per element that creates another array in one statement.

What may be slowing down Atom is the fact that a large amount of JSON data is being pushed over the socket. This is being done once for classes, once for functions (#46) and once for constants (#47). After that, all the providers still need to calculate suggestions based on these large data sets.

What may help mitigate the amount of data being sent over the wire is #43.
