### ISSUE TITLE
Update to core fails

### ISSUE THREAD

**Issue by justbane** [php-integrator/core#69]
<img width="1440" alt="screen shot 2016-12-22 at 2 19 23 pm" src="https://cloud.githubusercontent.com/assets/4744199/21442270/b4be6e1c-c851-11e6-9f2a-149bae8f028e.png">

Debug output: path must be a string

Anyone else?

**Comment by brad-jones** [comment]
Just remove and reinstall.

see: https://github.com/php-integrator/atom-base/issues/265

**Comment by richardtin** [comment]
I have the same issue. And it can be solved by re-installing.
But, `path must be a string` error still show after `Installing modules done`

**Comment by CatsMiaow** [comment]
![same](http://discord.tested.kr/20161223_113014.png)

**Comment by richardtin** [comment]
I found this issue can be solved by adding `package.json` back.
My test repo: https://github.com/richardtin/core

**Comment by netvision73** [comment]
Like @richardtin said, worked by removing `php-integrator-base`, but reinstalled with `apm install php-integrator-base` in terminal.

It didn't work installing it directly in Atom.

**Comment by Gert-dev** [comment]
As mentioned, the package `php-integrator-core` is no longer necessary and can be removed (strange that it is causing issues since it doesn't actually contain any CoffeeScript code and isn't used by anything anymore).

The base package will now automatically download the core and keep it up to date. It previously did this by installing it as a separate Atom package, but it now installs it via Composer, which allows me to select a specific version to install, automatically install the dependencies and reduce the size of th install, instead of always cloning the master branch from the core repository.

@CatsMiaow If the installation of the core fails, you should be able to find something in the developer tools, it will likely lists something like `Composer exited with status code 1` along with an error message.

**Comment by croaker000** [comment]
Tried all of the above in my Linux (Ubuntu) Atom 1.12.7 but still fails to install core. Dev-tools shows: "Composer exited with status code: 2" but no clue clue as to why...

**Comment by Gert-dev** [comment]
@croaker000 Could you try removing the --quiet flag in `CoreManager.coffee`? I'd expect `--quiet` to only surpress non-error output, but perhaps that's not the case.

**Comment by croaker000** [comment]
Not much difference:

/home/mart/.atom/packages/php-integrator-base/lib/ComposerService.coffee:76 Composer has errors to report: Installing php-integrator/core (2.1.0)

/home/mart/.atom/packages/php-integrator-base/lib/ComposerService.coffee:76 Composer has errors to report: 

/home/mart/.atom/packages/php-integrator-base/lib/ComposerService.coffee:76 Composer has errors to report:                                                                                              
  [InvalidArgumentException]                                                                 
  Project directory /home/mart/.atom/packages/php-integrator-base/core/2.1.0/ is not empty.  

/home/mart/.atom/packages/php-integrator-base/lib/ComposerService.coffee:76 Composer has errors to report: create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

/home/mart/.atom/packages/php-integrator-base/lib/ComposerService.coffee:79 Composer exited with status code: 1

**Comment by croaker000** [comment]
same output if /home/mart/.atom/packages/php-integrator-base/core/2.1.0/ is deleted

**Comment by Gert-dev** [comment]
Could you take a gander to see what is inside the `2.1.0` folder? If Composer claims it's not empty, something must be in there.

Also, are you possibly opening multiple projects at the same time when you start Atom? Perhaps there is some kind of conflict whilst multiple instances of the base package attempt to install to the same folder.

Finally, to debug more easily, you can always manually run the downloaded Composer from the `core` folder in the same manner as the base package does: `/path/to/php ./composer.phar create-project php-integrator/core ./2.1.0 --prefer-dist --no-dev`.

**Comment by croaker000** [comment]
OK, so deleting the 2.1.0 directory (which gets created on each install attempt) and then running your manual CLI command (abovbe) gives me nice debug feedback. It seems I was missing php-mbstring and php-xml Ubuntu packages. apt-get'ing those, deleting 2.1.0 again and running the command seemed to do the trick. Thanks.

**Comment by Gert-dev** [comment]
Glad to hear you got it working! Strange that Composer didn't give any proper errors about those after removing the `--quiet` flag. Perhaps it's because they are actually extensions instead of packages (although they are still listed in the package dependencies, so you'd expect it to report the errors all the same).
